name: Code Validation Run 
on: push
jobs:
  UnitTest:
    runs-on: ubuntu-latest

    steps:
      - name: 'Download the code from Git'
        uses: actions/checkout@v3

      - name: 'Install NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci 

      - name: Run unit tests
        run: npm test


  Deploy:
    runs-on: ubuntu-latest
      
    steps:
        - name: 'Download the code from Git'
          uses: actions/checkout@v3
      
        - name: 'Install NodeJS'
          uses: actions/setup-node@v3
          with:
            node-version: 18
      
        - name: Install dependencies
          run: npm ci 
      
        - name: Build project
          run: npm build

        - name: Deploy the solution
          run: echo "Deploying ......"

